repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: trailing-whitespace
        types_or: [c++, c, markdown, json, yaml]
      - id: end-of-file-fixer
        types_or: [c++, c, markdown, json, yaml]
      - id: check-case-conflict

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        types_or: [c++, c]
        args: [--style=file]

# Code quality only - no build or test validation
# Build validation should happen in CI, not pre-commit
