name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12]
        build_type: [Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Disable pre-commit hook
      run: |
        if [ -f .git/hooks/pre-commit ]; then
          mv .git/hooks/pre-commit .git/hooks/pre-commit.disabled
        fi
      shell: bash

    - name: Setup C++ (Linux)
      if: matrix.os == 'ubuntu-22.04'
      timeout-minutes: 5
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ libssl-dev ninja-build

    - name: Setup C++ (macOS)
      if: matrix.os == 'macos-12'
      timeout-minutes: 10
      run: |
        echo "Installing dependencies with brew..."
        brew update
        brew install ninja openssl
        echo "Setting OpenSSL environment variables..."
        echo "OPENSSL_ROOT_DIR=$(brew --prefix openssl)" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=$(brew --prefix openssl)/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

    - name: Setup C++ (Windows)
      if: matrix.os == 'windows-2022'
      timeout-minutes: 10
      run: |
        choco install ninja openssl
        echo "OPENSSL_ROOT_DIR=C:\Program Files\OpenSSL-Win64" >> $env:GITHUB_ENV

    - name: Configure CMake
      timeout-minutes: 5
      run: >
        cmake -B build -G Ninja
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DLLMCPP_BUILD_TESTS=ON

    - name: Build
      timeout-minutes: 15
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Test
      working-directory: build
      timeout-minutes: 10
      run: ctest --output-on-failure -C ${{ matrix.build_type }}

    - name: Upload build artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-${{ matrix.os }}-${{ matrix.build_type }}
        path: |
          build/CMakeFiles/*.log
          build/Testing/Temporary/LastTest.log 