name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
        build_type: [Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install cmake ninja

    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ cmake ninja-build libssl-dev

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install cmake ninja
        choco install openssl

    - name: Setup OpenSSL (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        echo "OPENSSL_ROOT_DIR=C:\Program Files\OpenSSL-Win64" >> $env:GITHUB_ENV
        echo "OPENSSL_INCLUDE_DIR=C:\Program Files\OpenSSL-Win64\include" >> $env:GITHUB_ENV
        echo "OPENSSL_LIBRARIES=C:\Program Files\OpenSSL-Win64\lib" >> $env:GITHUB_ENV

    - name: Disable pre-commit hook
      run: |
        if [ -f .git/hooks/pre-commit ]; then
          mv .git/hooks/pre-commit .git/hooks/pre-commit.disabled
        fi
      shell: bash

    - name: Configure CMake
      timeout-minutes: 5
      run: >
        cmake -B build -G Ninja
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DLLMCPP_BUILD_TESTS=ON
        ${{ matrix.os == 'windows-latest' && '-DOPENSSL_ROOT_DIR="C:/Program Files/OpenSSL-Win64"' || '' }}

    - name: Build
      timeout-minutes: 15
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Test
      working-directory: build
      timeout-minutes: 10
      run: ctest --output-on-failure -C ${{ matrix.build_type }}

    - name: Upload build artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-${{ matrix.os }}-${{ matrix.build_type }}
        path: |
          build/CMakeFiles/*.log
          build/Testing/Temporary/LastTest.log 