name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
        build_type: [Debug, Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup C++ (Linux)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ libssl-dev ninja-build

    - name: Setup C++ (macOS)
      if: matrix.os == 'macos-12'
      run: |
        brew install ninja openssl

    - name: Setup C++ (Windows)
      if: matrix.os == 'windows-2022'
      run: |
        choco install ninja openssl

    - name: Configure CMake
      run: >
        cmake -B build -G Ninja
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DLLMCPP_BUILD_TESTS=ON

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Test
      working-directory: build
      run: ctest --output-on-failure -C ${{ matrix.build_type }}

    - name: Upload build artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-${{ matrix.os }}-${{ matrix.build_type }}
        path: |
          build/CMakeFiles/*.log
          build/Testing/Temporary/LastTest.log 